datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/freelance
  user: root
  password: root1
  maxPoolSize: 10
hibernate:
  dialect-class: org.hibernate.dialect.MySQLDialect
  show-sql: true
  hbm2ddl: validate